name: github-programmers-rank

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 * * *'  # 매일 자정 실행

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: echo "Running npm install"
      - run: npm install

      - run: echo "Running build"
      - run: npm run build

      - run: |
          touch .env
          echo PROGRAMMERS_TOKEN_ID=${{ secrets.PROGRAMMERS_TOKEN_ID }} >> .env
          echo PROGRAMMERS_TOKEN_PW=${{ secrets.PROGRAMMERS_TOKEN_PW }} >> .env
          npm run start

      - name: Push changes to GitHub
        run: |
          git config --global user.email "github-programmers-rank@example.com"
          git config --global user.name "github-programmers-rank[bot]"
          git add .
          git commit -m "프로그래머스 순위 SVG 업데이트" || echo "No changes to commit"
          git push https://kdh044:${{ secrets.MY_GITHUB_TOKEN }}@github.com/kdh044/github-programmers-rank.git
